version: '3.1'
#Docker Networks
networks:
  fabric-network:

services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=fabric
      - MYSQL_USER=fabric
      - MYSQL_PASSWORD=1234
    ports:
      - '3306:3306'
    networks:
      - fabric-network

  api:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - './api:/application'
      - './.docker/api/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    networks:
      - fabric-network

  frontend:
    build: .docker/frontend
    stdin_open: true
    working_dir: /application
    volumes:
      - './frontend:/application'
      - './.docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - fabric-network

  php-fpm:
    build: .docker/php-fpm
    working_dir: /application
    volumes:
      - './api:/application'
      - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
    networks:
      - fabric-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    expose:
      - "1025"
    networks:
      - fabric-network